### ISSUE TITLE
Update link to the documentation in github description

### ISSUE THREAD

**Issue by daminetreg** [cps-org/cps#19]
Currently the link points to the personal doc deployment of @mwoehlke 

<img width="316" alt="image" src="https://github.com/cps-org/cps/assets/181726/078fad2a-5113-4eed-8917-bdb40e0b0047">

I see it's already deployed at https://cps-org.github.io/cps/, therefore I think it's safe to update the link in the description of the repository.

**Comment by mwoehlke** [comment]
Fixed; thanks!
