### ISSUE TITLE
Getting Started Doc

### ISSUE THREAD

**Issue by andresrcc** [cps-org/cps#21]
Would be great to have a "getting started" type document so we could start playing around with some samples.

**Comment by bretbrownjr** [comment]
@andresrcc I created https://github.com/cps-org/cps-wiki thinking it could serve exactly this purpose. I think you, me, and @mwoehlke can find a time as early as this week to get this launched. If you have time now.

**Comment by bretbrownjr** [comment]
When we get an MVP for this, I'll consider https://github.com/cps-org/cps/issues/28 closed as well.

Let's make sure we have prominent links from the CPS repo itself to the wiki, or at least the most interesting parts of a wiki, like Getting Started and FAQ.

**Comment by andresrcc** [comment]
Sounds great will take a look!

**Comment by bretbrownjr** [comment]
I've done some updates to [the cps-wiki](https://github.com/cps-org/cps-wiki/wiki/Welcome). If we still want to see more, let's open new, more specific tickets about what's missing. Just editing the wiki directly is also a good idea if opening an issue seems not worth it.
