### ISSUE TITLE
CPS should have a wiki

### ISSUE THREAD

**Issue by mwoehlke** [cps-org/cps#28]
It would be helpful if we could add documentation (e.g. FAQs) in a more freely editable format than contributing to the official repository. On the other hand, we don't necessarily want it to be open to anonymous editing.

We should create a new repo in the organization to host a wiki that can have a more permissive list of users with write permission.

**Comment by bretbrownjr** [comment]
That works for me as long as it's easy to discover from the CPS README.

**Comment by mwoehlke** [comment]
https://github.com/cps-org/cps-wiki/wiki/ exists now.
