### ISSUE TITLE
Refer to Semantic Line Breaks website for formatting

### ISSUE THREAD

**Issue by jwakely** [cps-org/cps#87]
https://github.com/cps-org/cps/blob/79401d2807137de65d81f684297d09e0a96b2e6a/development.rst?plain=1#L44-L55

It would probably make sense to reference https://sembr.org/ here

**Comment by mwoehlke** [comment]
Added, thanks! I didn't know about sembr.org; as best I can recall, I'd developed similar habits all on my own (seeing as they are quite obviously beneficial for version-controlled prose). It's useful to be able to cite other people supporting a similar system, though!
